<b> From that IRIS dataset we need to apply KNN Algorithm implementation </b> 

In [26]:
# importing the libraries required

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
data=pd.read_csv("IRIS.csv") # Reading the dataset

In [28]:
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [39]:
print(data.tail())

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica


In [37]:
print(data.shape)

(150, 5)


In [29]:
x=data.iloc[:,:-1]  # loading feature values i,e from dataset all rows and columns except last column
y=data.iloc[:,4] # loading prediction values from data set i,e all rows and last column only.

In [30]:
print(x) # printing all the features
print("") 

print(y) # printing predicted values from dataset

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: ob

In [31]:
from sklearn.model_selection import train_test_split  # to split the training and testing data we are imporint this module
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)  # we splitted accordingly and kept the size of testing as 20%

In [32]:
from sklearn.preprocessing import StandardScaler # to scale the data
scaler=StandardScaler() 
scaler.fit(x_train) 
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [33]:
from sklearn.neighbors import KNeighborsClassifier # as it is classification data, imported KNeighborsClassifier module
classifier=KNeighborsClassifier(n_neighbors=7) # keeping N value as 7
classifier.fit(x_train,y_train) #fitting

KNeighborsClassifier(n_neighbors=7)

In [34]:
y_prediction=classifier.predict(x_test) # from the model we made, predicting for testing data features 

In [35]:
from sklearn.metrics import confusion_matrix 
print("")
print(confusion_matrix(y_test,y_prediction)) # this evaluates errors and finds accuracy %


[[ 9  0  0]
 [ 0 16  2]
 [ 0  0  3]]
