In [1]:
! pip install numpy


In [3]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
b=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


# The below cell is giving error ?


In [13]:
import timeit 

timetit.timeit[np.range(10000) **3]

NameError: name 'timetit' is not defined

In [17]:
print(np.ones((3,5)))
print(" ")
print(np.zeros((6,8)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
print(np.random.seed(10))

None
